#ifndef NBA97_GAME_ROTATION_MATRIX_H
#define NBA97_GAME_ROTATION_MATRIX_H

#include "game_match_clocks.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef Nba97GameMatchClocksWord Nba97GameRotationMatrixWord;
typedef Nba97GameMatchClocksMachine Nba97GameRotationMatrixMachine;
typedef Nba97GameMatchClocksAccess Nba97GameRotationMatrixAccess;

typedef struct Nba97GameRotationMatrixContext {
  Nba97GameTextMemory memory;
  size_t operation_budget;
  Nba97GameRotationMatrixMachine machine;
  Nba97GameRotationMatrixAccess *access_journal;
  size_t access_journal_capacity;
} Nba97GameRotationMatrixContext;

typedef struct Nba97GameRotationMatrixProgress {
  size_t operations;
  size_t accesses;
  size_t reads;
  size_t stores;
  size_t access_events;
  size_t multiply_count;
  uint32_t stopped_pc;
  uint32_t stopped_address;
  uint32_t instruction_count;
  Nba97GameRotationMatrixWord angle_x;
  Nba97GameRotationMatrixWord angle_y;
  Nba97GameRotationMatrixWord angle_z;
  Nba97GameRotationMatrixWord returned_value;
  Nba97GameRotationMatrixMachine machine;
  uint8_t completed;
} Nba97GameRotationMatrixProgress;

/*
 * PS1 SUBROUTINE
 * Program: GAMEONLY
 * Address: 0x80056080
 * Range: 0x80056080..0x800562CB (inclusive)
 * Source size: 588 bytes / 147 instructions
 * Evidence: fresh Ghidra game_80056080.txt; instruction SHA-256
 * dead4863c9e67d31eb16d64b222c9a6e5b13a8d118ff0cc66251fac9928a5133
 *
 * Purpose: Build the source fixed-point 3x3 rotation matrix from three signed
 * actor angles and the packed sine/cosine table.
 * Inputs: All 32 live GPRs and HI/LO; a0 points to three signed halfword
 * angles, a1 points to matrix storage, and 0x800B3254 holds 4096 packed table
 * words.
 * Returns: v0 is the original a1 value; all source-written temporaries and the
 * last unsigned MULTU HI/LO remain live, while SP and every unwritten GPR are
 * preserved and JR consumes live ra.
 * Guest memory: Reads angles at a0+0/+2/+4 and packed table words, then stores
 * halfwords to a1+4,+A,+10,+0,+2,+6,+C,+8,+E in exact source order.
 * Calls: None observed.
 * Original quirks: Signed angles wrap through negation and mask 0xFFF; MULTU
 * uses unsigned 32-bit operands even for sign-extended values; negation occurs
 * before selected SRA 12 operations; the third table lookup occurs after the
 * first three stores and therefore observes output/table aliases.
 * Native mapping: Guest addresses remain validated uint32_t mapped values with
 * per-byte knownness, exact prefixes, and no guest-to-host pointer casts;
 * packed lookup words are generated by synthetic callers or runtime state.
 */
int nba97_game_rotation_matrix(Nba97GameRotationMatrixContext *,
                               Nba97GameRotationMatrixProgress *);

#ifdef __cplusplus
}
#endif
#endif
