#include "user_setup_session.hpp"
#include <algorithm>
#include <array>
#include <cstring>
#include <iostream>
#include <stdexcept>
#include <string>

using nba97::UserSetupSession;
namespace {
unsigned checks=0;
void check(bool ok,const char* why) {
    ++checks;
    if(!ok) throw std::runtime_error(why);
}

// Source data80024BA4..80024C43 and37010 placement calls. These expected
// coordinates are not generated by the placement implementation under test.
struct Layout {
    unsigned count,base;
    uint8_t included;
    int name_y,stride,away,neutral,home;
    std::array<unsigned,8> physical;
};
constexpr Layout layouts[]{
    {2,0,0x11,88,75,50,180,318,{0,4,5,6,7,1,2,3}},
    {5,2,0x1f,78,27,80,216,350,{0,1,2,3,4,5,6,7}},
    {5,2,0xf1,78,27,80,216,350,{0,4,5,6,7,1,2,3}},
    {8,7,0xff,73,17,106,230,380,{0,1,2,3,4,5,6,7}}
};
const std::array<uint8_t,8> neutral{};

void samePlacement(const Nba97UserPlacement& a,const Nba97UserPlacement& b,const char* why) {
    check(a.text_alive==b.text_alive &&
          std::equal(a.text_x,a.text_x+8,b.text_x) && std::equal(a.text_y,a.text_y+8,b.text_y) &&
          std::equal(a.marker_x,a.marker_x+15,b.marker_x) && std::equal(a.marker_y,a.marker_y+15,b.marker_y),why);
}
void textAt(const UserSetupSession& s,unsigned c,int x,int y,const char* why) {
    const auto& p=s.placement();check(p.text_x[c]==x && p.text_y[c]==y,why);
}
void markerAt(const UserSetupSession& s,unsigned m,int x,int y,const char* why) {
    const auto& p=s.placement();check(p.marker_x[m]==x && p.marker_y[m]==y,why);
}
void rebuilt(const UserSetupSession& s,unsigned topology,uint8_t alive) {
    const auto& expected=layouts[topology];
    check(s.placement().text_alive==alive,"rebuild retains old groups and creates included physical groups");
    for(unsigned row=0;row<8;++row)
        textAt(s,expected.physical[row],700,66+18*int(row),"rebuild hides text in new physical row order");
    for(unsigned m=0;m<15;++m)
        markerAt(s,m,700,66+18*int(m),"rebuild hides all fifteen source markers");
}
void input(UserSetupSession& s,unsigned c,uint16_t token,int clock) {
    s.key(c,token,true);s.step(clock);s.key(c,token,false);
}
void dismissHelp(UserSetupSession& s,unsigned c) {
    // A changed nonzero acknowledgement works during growth or after readiness.
    // Only the invoking controller changes; other rows' pending input survives.
    const uint16_t ack=s.priorMask()==0x800 ? 0x400:0x800;
    s.key(c,0xffff,false);s.key(c,ack,true);
    for(unsigned i=0;i<100 && s.help().phase!=NBA97_HELP_RETURN_BARRIER;++i)s.tickHelp();
    check(s.help().phase==NBA97_HELP_RETURN_BARRIER,"Help reaches its final held-input barrier");
    s.key(c,ack,false);s.tickHelp();
    check(s.help().phase==NBA97_HELP_CLOSED,"changed invoking input returns Help");
}
void editorLocalsEqual(const Nba97UserSetup& a,const Nba97UserSetup& b) {
    check(std::equal(a.side,a.side+8,b.side) && std::equal(a.assignment,a.assignment+8,b.assignment) &&
          std::equal(a.profile,a.profile+8,b.profile) && std::equal(a.alphabet,a.alphabet+8,b.alphabet) &&
          std::equal(a.cursor,a.cursor+8,b.cursor) && std::equal(a.existing,a.existing+8,b.existing) &&
          !std::memcmp(a.draft,b.draft,sizeof(a.draft)),"rebuild must preserve logical editor and assignment fields");
}

void allTopologies() {
    const std::array<uint8_t,8> assignments{{0,1,2,0,1,2,0,1}};
    for(unsigned topology=0;topology<4;++topology) {
        const auto& expected=layouts[topology];
        UserSetupSession s;s.open(assignments,{},0);s.setControllers(topology,0xff);
        check(s.placement().text_alive==0,"open clears text ownership");
        s.primeEntryTopology();rebuilt(s,topology,expected.included);
        const auto hidden=s.placement();s.primeEntryTopology();s.tickPresentation();
        samePlacement(s.placement(),hidden,"repeated entry priming and presentation do not place rows");
        check(s.step(6).empty(),"elapsed six cannot visit controller rows");
        samePlacement(s.placement(),hidden,"closed clock gate preserves rebuild hiding");
        s.step(7);
        for(unsigned row=0;row<expected.count;++row) {
            const unsigned c=expected.physical[row];
            const int side=assignments[c]==1 ? 2:assignments[c]==2 ? 0:1;
            const int x=side==0 ? expected.away:side==1 ? expected.neutral:expected.home;
            textAt(s,c,side==1 ? 700:256,expected.name_y+int(row)*expected.stride,"connected row text placement");
            markerAt(s,expected.base+row,x,73+int(row)*expected.stride,"connected row marker placement");
        }
        const auto placed=s.placement();s.setControllers(topology,0x55);s.step(8);
        samePlacement(s.placement(),placed,"live disconnect alone does not hide retained placement");
        s.step(14);
        for(unsigned row=0;row<expected.count;++row) {
            const unsigned c=expected.physical[row];
            if(!(0x55&(1u<<c))) {
                textAt(s,c,700,expected.name_y+18*int(row),"disconnected text uses source eighteen-pixel hide spacing");
                markerAt(s,expected.base+row,700,66+18*int(row),"disconnected marker uses source hide origin");
                check(s.state().side[c]==1 && s.state().profile[c]==-2,"visited disconnect clears local assignment/profile");
            }
        }
    }
}

void gatedRebuildAndReconnection() {
    std::array<uint8_t,8> assignments{};assignments[0]=1;assignments[4]=2;
    UserSetupSession s;s.open(assignments,{},0);s.setControllers(3,0xff);s.step(0);s.step(7);
    const auto before=s.placement();const auto logical=s.state();s.setControllers(0,0xff);
    for(unsigned i=0;i<4;++i) {s.step(8);samePlacement(s.placement(),before,"pending topology retains all old placement");}
    s.step(8);rebuilt(s,0,0xff);editorLocalsEqual(logical,s.state());
    const auto hidden=s.placement();s.step(13);
    samePlacement(s.placement(),hidden,"adoption does not bypass elapsed-six gate");
    s.step(14);textAt(s,0,256,88,"home text restored after first timed visit");
    textAt(s,4,256,163,"physical four uses second non-multitap row");
    markerAt(s,0,318,73,"home marker restored");markerAt(s,1,50,148,"away marker restored");
    check(s.placement().text_alive==0xff,"old excluded labels remain allocated but hidden");
    const auto visible=s.placement();s.step(15);
    samePlacement(s.placement(),visible,"matching active observation does not hide rows again");
    s.setControllers(0,0);s.step(16);
    samePlacement(s.placement(),visible,"closed gate must not follow instantaneous connection state");
    s.step(21);textAt(s,4,700,106,"timed disconnect hides physical four at disconnected text y");
    markerAt(s,1,700,84,"timed disconnect hides second marker at disconnected y");
    const auto disconnected=s.placement();s.setControllers(0,0x11);s.step(22);
    samePlacement(s.placement(),disconnected,"reconnection cannot reveal before a timed visit");
    s.step(28);textAt(s,4,700,163,"reconnected controller stays logically neutral");
    markerAt(s,1,180,148,"next timed visit reveals reconnected neutral marker");
}

void editorRebuild() {
    UserSetupSession s;s.open(neutral,{},0);s.setControllers(0,1);s.step(0);
    // Synthetic width isolates scheduling; this does not test the extracted font.
    constexpr char alphabet[]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789?!-._'";
    static_assert(sizeof(alphabet)==69,"source alphabet length");
    std::array<char,68> letters{};std::copy_n(alphabet,68,letters.begin());
    s.configureEditor(letters,[](const char* value){return int(std::strlen(value))*8;});
    input(s,0,4,7);input(s,0,1,14);input(s,0,0x800,21);
    check(s.state().alphabet[0]==0 && !std::strcmp(s.state().draft[0],"A"),"editor entered through ordinary controls");
    const auto logical=s.state();const auto ids=s.profileIds();s.setControllers(1,1);
    for(unsigned i=0;i<5;++i)s.step(22);
    rebuilt(s,1,0x1f);editorLocalsEqual(logical,s.state());
    check(s.profileIds()==ids,"rebuild cannot modify profile identity mapping");
    const auto hidden=s.placement();s.step(27);
    samePlacement(s.placement(),hidden,"editor stays hidden while timed gate is closed");
    s.step(28);textAt(s,0,256,78,"editor row tail restores joined text at new topology y");
    markerAt(s,2,350,73,"editor row tail restores new-layout home marker");
    editorLocalsEqual(logical,s.state());
}

void neutralHelpTail() {
    std::array<uint8_t,8> assignments{};assignments[0]=1;
    UserSetupSession s;s.open(assignments,{},0,0x20);s.setControllers(0,0x11);s.step(0);s.step(7);
    input(s,0,8,14);textAt(s,0,700,88,"moving to neutral hides text");
    markerAt(s,0,700,73,"moving to neutral hides marker for one completed visit");
    s.key(0,0x20,true);const auto actions=s.step(21);
    check(actions.size()==1 && actions[0].event==NBA97_USER_HELP && s.hasPendingRowTail(),"Help suspends current row tail");
    check(!s.state().hide_marker[0],"ordinary input has already reset the neutral pulse latch");
    markerAt(s,0,700,73,"early pulse reset must not reveal marker before Help returns");
    s.openHelp({111,70,290,140},0);const auto blocked=s.placement();
    for(unsigned i=0;i<12;++i) {s.tickHelp();s.tickPresentation();s.step(22+int(i));}
    samePlacement(s.placement(),blocked,"modal presentations cannot execute pending row tail");
    dismissHelp(s,0);s.step(22);
    check(!s.hasPendingRowTail(),"return executes pending tail exactly once");
    textAt(s,0,700,88,"neutral Help return keeps name hidden");
    markerAt(s,0,180,73,"neutral Help return completes marker restoration");
}

void disconnectDuringHelp() {
    std::array<uint8_t,8> assignments{};assignments[0]=1;
    UserSetupSession s;s.open(assignments,{},0,0x20);s.setControllers(0,0x11);s.step(0);s.step(7);
    s.key(0,0x20,true);s.step(14);s.openHelp({111,70,290,140},0);
    const auto blocked=s.placement();s.setControllers(1,0x10);s.key(4,4,true);s.step(50);
    samePlacement(s.placement(),blocked,"unplug during Help preserves preceding placement");
    dismissHelp(s,0);const auto resumed=s.step(51);
    check(s.topology()==0 && resumed.size()==1 && resumed[0].controller==4,
          "continuation retains topology and polls only the next live physical row");
    textAt(s,0,256,88,"invoking row completes connected branch despite later unplug");
    markerAt(s,0,318,73,"invoking row tail does not re-check connection");
    textAt(s,4,256,163,"later row uses live connection and its pending Right input");
    markerAt(s,1,318,148,"physical four completes old-topology home marker");
    s.step(52);textAt(s,0,700,88,"next fresh timed pass finally disconnects invoking row");
    markerAt(s,0,700,66,"fresh disconnection uses separate marker hide origin");

    assignments[4]=2;
    UserSetupSession later;later.open(assignments,{},0,0x20);later.setControllers(0,0x11);later.step(0);later.step(7);
    later.key(0,0x20,true);later.step(14);later.openHelp({111,70,290,140},0);later.setControllers(0,1);
    textAt(later,4,256,163,"later unplugged row stays visible before its suspended visit");
    dismissHelp(later,0);later.step(15);
    textAt(later,4,700,106,"later row re-checks live connection on resume");
    markerAt(later,1,700,84,"later disconnected marker is hidden by resumed row");
}

void multipleBlockedRows() {
    UserSetupSession s;s.open(neutral,{},0,0x20);s.setControllers(3,0xff);s.step(0);
    s.key(3,0x20,true);s.key(5,0x20,true);
    auto actions=s.step(7);
    check(actions.size()==1 && actions[0].controller==3 && s.hasPendingRowTail(),"first blocked row is physical three");
    for(unsigned row=0;row<3;++row)markerAt(s,7+row,230,73+17*int(row),"earlier rows already completed");
    for(unsigned row=3;row<8;++row)check(s.placement().marker_x[7+row]==700,"blocked and later rows stay rebuild-hidden");
    s.openHelp({111,70,290,140},0);dismissHelp(s,3);actions=s.step(8);
    check(actions.size()==1 && actions[0].controller==5 && s.hasPendingRowTail(),"second Help interrupts the same source pass");
    markerAt(s,10,230,124,"first invoking tail completed before next row");
    markerAt(s,11,230,141,"intervening row completed before second Help");
    for(unsigned row=5;row<8;++row)check(s.placement().marker_x[7+row]==700,"second blocked tail and later rows remain hidden");
    s.openHelp({111,70,290,140},0);dismissHelp(s,5);s.step(9);
    check(!s.hasPendingRowTail(),"second return finishes the suspended pass");
    for(unsigned row=0;row<8;++row)markerAt(s,7+row,230,73+17*int(row),"all rows placed only after both continuations");
}

void terminalAndExcludedRows() {
    std::array<uint8_t,8> assignments{};assignments[0]=1;
    for(uint16_t token:{uint16_t(0x80),uint16_t(0x100)}) {
        UserSetupSession s;s.open(assignments,{},0);s.setControllers(0,0x11);s.step(0);s.step(7);
        auto expected=s.placement();expected.text_alive=0;s.key(0,token,true);s.step(8);
        samePlacement(s.placement(),expected,"terminal return clears text ownership but does not reposition markers");
        s.setControllers(3,0xff);s.step(100);
        samePlacement(s.placement(),expected,"terminal owner cannot restore placement on later input");

        UserSetupSession adopted;adopted.open(assignments,{},0);adopted.setControllers(3,0xff);adopted.step(0);adopted.step(7);
        adopted.setControllers(1,0xff);for(unsigned i=0;i<4;++i)adopted.step(8);
        adopted.key(0,token,true);adopted.step(8);
        check(adopted.topology()==1 && adopted.state().result==(token==0x80 ? 6:-1),"fifth topology observation precedes terminal global gate");
        rebuilt(adopted,1,0);
        adopted.open(neutral,{},200);check(adopted.placement().text_alive==0,"reentry discards old text ownership");
        adopted.setControllers(0,1);adopted.primeEntryTopology();rebuilt(adopted,0,0x11);
    }

    assignments[5]=1;
    UserSetupSession s;s.open(assignments,{},0,0x20);s.setControllers(3,0xff);s.step(0);s.step(7);
    s.setControllers(1,0xff);for(unsigned i=0;i<5;++i)s.step(8);
    check(s.state().side[5]==2,"closed rebuild does not clear topology-excluded assignment");
    s.key(0,0x20,true);s.step(14);s.openHelp({111,70,290,140},0);
    check(s.state().side[5]==2,"blocking first row delays excluded cleanup");
    dismissHelp(s,0);s.step(15);
    check(s.state().side[5]==1 && s.state().profile[5]==-2,"excluded cleanup follows all resumed included rows");
    check(s.placement().text_alive==0xff,"excluded old text group remains owned after logical cleanup");
    textAt(s,5,700,156,"excluded group retains hidden rebuild coordinates");
}
}

int main() {
    try {
        allTopologies();gatedRebuildAndReconnection();editorRebuild();neutralHelpTail();
        disconnectDuringHelp();multipleBlockedRows();terminalAndExcludedRows();
        std::cout<<"USER SETUP VISIBILITY PASS: "<<checks<<" session placement assertions; synthetic input, no assets or saves\n";
        return 0;
    } catch(const std::exception& e) {std::cerr<<e.what()<<'\n';return 1;}
}
