#!/usr/bin/env python3
"""Small Trade entry ledger; reuse the existing block/denominator validator."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import subprocess

from verify_reorder_rosters import calculate as validate_blocks

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/decomp/trade_rosters.json"
REPORT = ROOT / "reports/trade_rosters.json"
DOC = ROOT / "docs/trade_rosters_progress.md"


def calculate(config=None, inventory=None):
    config = config if config is not None else json.loads(CONFIG.read_text(encoding="utf-8"))
    validated = validate_blocks(config, inventory)
    for owner in config['functions']:
        evidence=owner.get('block_evidence',{})
        if set(evidence)!=set(owner['accounted_blocks']):
            raise ValueError('Trade requires exact per-block evidence')
        for block in evidence.values():
            if not block.get('behavior') or not block.get('tests') or not set(block['tests'])<=set(owner['tests']):
                raise ValueError('Trade block needs behavior and owner-declared tests')
        if '0x80056D28' in owner['accounted_blocks']:
            callbacks={c['address'] for c in config.get('selection_contracts',[])}
            if not {'0x80056B44','0x80056C50'}<=callbacks:
                raise ValueError('Trade handoff needs both indirect callback contracts')
    return {key: validated[key] for key in (
        "schema_version", "scope", "measurement", "instructions", "functions",
        "slices", "tests_executed_by_static_report", "dependency_policy",
        "shared_contracts", "screen_contracts", "selection_contracts")}


def markdown(report):
    count = report["instructions"]
    contracts='\n'.join(f"| `{c['address']}` | {c['scope']} | {c['integration_pending']} |"
        for c in report['shared_contracts']+report['screen_contracts']+report['selection_contracts'])
    return f"""# Trade Players: entry progress

Generated by `python tools/verify_trade_rosters.py`. Do not hand-edit.

| Narrow entry scope | Accounted | Pending |
|---|---:|---:|
| `80056CD0` wrapper | {count['accounted']} / {count['total']} | {count['pending']} |

**{count['percent']:.2f}% of this wrapper is source-accounted, not percent of Trade Players complete.**
Static reporting does not run tests or prove original execution equivalence.
The Trade card now opens a native screen. Its host/asset/save regression is
separate: `python tools/verify_trade_screen.py` (requires private assets).
Working integration does not automatically earn instruction-block credit.

{report['functions'][0]['note']}

{report['dependency_policy']}

## Tested call contracts, not callee-body coverage

| Original helper | Native contract | Outside this claim |
|---|---|---|
{contracts}

The original blocking call is an owned native controller plus a frame pump.
The host consumes signed selector results:1 accept,-1 cancel,2 View,3 Compare.
This wrapper accounting does not settle the original post-child rollback
boundary or prove exact input, audio, animation or rendering fidelity.

See [implementation plan and evidence](trade_rosters_workflow.md).

```powershell
./scripts/verify_trade_rosters.ps1
python tools/verify_trade_rosters.py --check
```
"""


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run_native(executable, config):
    executable = Path(executable).resolve(strict=True)
    completed = subprocess.run([str(executable)], capture_output=True, text=True, timeout=30)
    print(completed.stdout, end="")
    if completed.stderr:
        print(completed.stderr, end="")
    actual = [line.removeprefix("TRADE PASS ") for line in completed.stdout.splitlines()
              if line.startswith("TRADE PASS ")]
    passed = completed.returncode == 0 and sorted(actual) == sorted(config["core_tests"])
    sources = [CONFIG, ROOT / config["inventory"], ROOT / "src/recovered/roster_trade.c",
               ROOT / "src/recovered/roster_trade.h", ROOT / "src/recovered/roster_reorder.c",
               ROOT / "tests/roster_trade_test.cpp"]
    evidence = {"schema_version": 1, "executed_utc": datetime.now(timezone.utc).isoformat(),
                "status": "passed" if passed else "failed", "returncode": completed.returncode,
                "scenarios": actual, "executable": str(executable), "executable_sha256": sha(executable),
                "source_sha256": {str(p.relative_to(ROOT)): sha(p) for p in sources},
                "stdout": completed.stdout, "stderr": completed.stderr,
                "limitation": "Native entry/constructor/callback/return contracts only; host execution and original comparison have separate evidence."}
    path = ROOT / ".local/reports/trade_rosters_run.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
    if not passed:
        raise ValueError("native test failed or scenario manifest differs")
    print(f"TRADE TESTS {len(actual)}/{len(config['core_tests'])}; evidence={path.relative_to(ROOT)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--native-test", help="Run the freshly built Trade entry test executable")
    args = parser.parse_args()
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    report = calculate(config)
    for path, content in ((REPORT, json.dumps(report, indent=2) + "\n"), (DOC, markdown(report))):
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise ValueError(f"stale report: {path.relative_to(ROOT)}")
        else:
            path.write_text(content, encoding="utf-8")
    if args.native_test:
        run_native(args.native_test, config)
    count = report["instructions"]
    print(f"TRADE ENTRY ACCOUNTING {count['accounted']}/{count['total']}; {count['pending']} pending")
    print("TRADE FEATURE acceptance/evidence: docs/trade_rosters_workflow.md; entry accounting is not feature or fidelity completion")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, KeyError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"TRADE VERIFY FAIL: {error}")
